export const USERS_DATA_RECEIVED = "USERS_DATA_RECEIVED";
export const MAINFORM_DATA_CHANGE = "MAINFORM_DATA_CHANGE"
export const CLEAR_MAIN_FORM = "CLEAR_MAIN_FORM";
export const ADD_NEW_USERDATA = "ADD_NEW_USERDATA";
export const DELETE_FROM_USERLIST = "DELETE_FROM_USERLIST";
